---
- name: Update AAP API credentials by name
  hosts: localhost
  gather_facts: false
  vars:
    aap_base_url: "https://"  # AAPのベースURL
    aap_username: ""  # AAPのユーザー名
    aap_password: ""  # AAPのパスワード
    api_endpoint: "/api/controller/v2/credentials/"  # Credentials APIエンドポイント
    filter_name: "AWS"  # フィルタするシークレット名を指定
    new_access_key: ""  # 新しいアクセスキー
    new_secret_key: ""  # 新しいシークレットキー

  tasks:
    - name: Get credentials list
      ansible.builtin.uri:
        url: "{{ aap_base_url }}{{ api_endpoint }}"
        method: GET
        user: "{{ aap_username }}"
        password: "{{ aap_password }}"
        force_basic_auth: true
        validate_certs: false  # 必要に応じて証明書検証を無効化
      register: credentials_response

    - name: Find credential ID by name
      ansible.builtin.set_fact:
        credential_id: >-
          {{ (credentials_response.json.results | selectattr('name', 'equalto', filter_name) | list | first).id }}

    - name: Update credentials with new access and secret keys
      ansible.builtin.uri:
        url: "{{ aap_base_url }}{{ api_endpoint }}{{ credential_id }}/"
        method: PATCH
        user: "{{ aap_username }}"
        password: "{{ aap_password }}"
        force_basic_auth: true
        validate_certs: false  # 必要に応じて証明書検証を無効化
        headers:
          Content-Type: "application/json"
        body_format: json
        body:
          inputs:
            username: "{{ new_access_key }}"
            password: "{{ new_secret_key }}"
      register: update_response
      no_log: true  # ログを非表示にするための設定

    - name: Display update response
      ansible.builtin.debug:
        var: update_response.json
