---
- name: Access AAP API to list credentials with filter
  hosts: localhost
  gather_facts: false
  vars:
    aap_base_url: "https://"  # AAPのベースURL
    aap_username: ""  # AAPのユーザー名
    aap_password: ""  # AAPのパスワード
    api_endpoint: "/api/controller/v2/credentials/"  # 修正されたCredentials APIエンドポイント
    filter_name: "AWS"  # フィルタするシークレット名を指定

  tasks:
    - name: Make API request to list credentials
      ansible.builtin.uri:
        url: "{{ aap_base_url }}{{ api_endpoint }}"
        method: GET
        user: "{{ aap_username }}"
        password: "{{ aap_password }}"
        force_basic_auth: true
        validate_certs: false  # 必要に応じて証明書検証を無効化
      register: api_response

    - name: Filter credentials with specified name
      ansible.builtin.set_fact:
        filtered_credentials: >-
          {{ api_response.json.results | selectattr('name', 'equalto', filter_name) | list }}

    - name: Display filtered credentials
      ansible.builtin.debug:
        var: filtered_credentials
