---
- name: "IAM Identity Center グループリストの取得 (AssumeRole)"
  hosts: localhost
  gather_facts: false
  vars_files:
    - vars/main.yml

  tasks:
    - name: "IAMロールを引き受ける"
      amazon.aws.sts_assume_role:
        role_arn: "{{ assume_role_arn }}"  # vars/main.ymlで定義
        role_session_name: "AnsibleSession"
      register: assumed_role

    - name: "環境変数を設定"
      ansible.builtin.set_fact:
        aws_env:
          AWS_ACCESS_KEY_ID: "{{ assumed_role.sts_creds.access_key }}"
          AWS_SECRET_ACCESS_KEY: "{{ assumed_role.sts_creds.secret_key }}"
          AWS_SESSION_TOKEN: "{{ assumed_role.sts_creds.session_token }}"
          AWS_DEFAULT_REGION: "{{ aws_region }}"

    - name: "IAM Identity Center グループリストの取得"
      ansible.builtin.command: >
        aws identitystore list-groups
          --identity-store-id "{{ identity_store_id }}"
      environment: "{{ aws_env }}"
      register: list_groups_result
      changed_when: false

    - name: "グループリスト取得結果のデバッグ"
      ansible.builtin.debug:
        var: list_groups_result.stdout | from_json
