---
- name: Gather EC2 information
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Gather information about specified instances
      amazon.aws.ec2_instance_info:
        region: ap-northeast-1
        filters:
          "tag:Name": "rhel9"
