---
- name: Gather EC2 information
  hosts: localhost
  gather_facts: false
  vars:
    region: ap-northeast-1
    ec2_name: amazonlinux

  tasks:
    - name: Gather information about all instances
      amazon.aws.ec2_instance_info:
        region: "{{ region }}"
        filters:
          "tag:Name": "{{ ec2_name }}"
